name: vue3

on:
  push:
    branches: [dev,master]

jobs:
  lint:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      - name: insatll
        run: yarn
