name: vue3

on:
  push:
    branches: [dev,master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      - name: install
        run: yarn -v && yarn

      - name: lint
        run: yarn eslint . --ext .js,.jsx,.ts,.tsx
#         run: yarn lint
